### ISSUE TITLE
Adding some description to all the topics

### ISSUE THREAD

**Issue by Nexengineer** [Nexengineer/DSA-PREP#19]
Add some theoretical knowledge to the individual topics in Readme.md file.

**Comment by Nevish-302** [comment]
can you assign this to me?
Also how descriptive should the knowledge be , like with pictures and such or just textual explanation?

**Comment by Nexengineer** [comment]
Descriptive - Just add text in the shoes of a person trying to explain something to someone
Media - You can use gifs/images/links whatever you like.

Tip: Instead of putting everything in the same readme file. You can create folder-specific readme's. It is all up to you.

Assigning you

**Comment by neeraj542** [comment]
if something is there for me then assign me for my 1st PR

**Comment by Nexengineer** [comment]
I think you can pickup adding media to the readme. If you are intrested @neeraj542

**Comment by neeraj542** [comment]
I'm looking to complete my 1st PR

**Comment by Hanuvesh** [comment]
i can perfectly complete this task , please assign to me

**Comment by Nexengineer** [comment]
@Hanuvesh assigned you

**Comment by neeraj542** [comment]
Sir, i can also work in this issue

**Comment by Nexengineer** [comment]
@neeraj542

**Comment by neeraj542** [comment]
sir I'm working on this ..Have to merge PR
