### ISSUE TITLE
Create a readme file

### ISSUE THREAD

**Issue by Nexengineer** [Nexengineer/DSA-PREP#4]

**Comment by Aratrik-02** [comment]
I would like to give this one a try

**Comment by Nexengineer** [comment]
Thanks man! go ahead.  Do raise a PR

**Comment by Aratrik-02** [comment]
I raised a PR but its showing this
![image](https://user-images.githubusercontent.com/75318952/193447385-7cdc5531-aa06-4546-bbb0-26505e8874ab.png)

**Comment by Aratrik-02** [comment]
The issue has been resolved :)

**Comment by Aratrik-02** [comment]
This issue has been addressed in PR #17 @Nexengineer

**Comment by Nexengineer** [comment]
Hi, 

Your hyper links to folders are not working. Please have a look and close it

**Comment by Nexengineer** [comment]
@Aratrik-02 you can use relative path

**Comment by Aratrik-02** [comment]
Okay i will change it 😅

**Comment by Aratrik-02** [comment]
@Nexengineer the links are now working properly. It has been addressed in #22

**Comment by Nexengineer** [comment]
thanks @Aratrik-02
