### ISSUE TITLE
Add more beginner questions for recursion

### ISSUE THREAD

**Issue by Nexengineer** [Nexengineer/DSA-PREP#5]

**Comment by thechangamunda** [comment]
I would like to contribute in it, are there any language specifications?

**Comment by Nexengineer** [comment]
Hi Please go ahead. There is some contribution rules. please go through them. After you are done raise a pr. Thanks

**Comment by hraj37378** [comment]
I would like to contribute too...I have done Data Structures and algorithms from GFG and practiced more than 250+ problems on the same platform.

**Comment by rishabhyadav23** [comment]
please assign me on this issue
