### ISSUE TITLE
Add as many questions !!! As you want

### ISSUE THREAD

**Issue by Nexengineer** [Nexengineer/DSA-PREP#8]

**Comment by yashg-116** [comment]
Hello, I would like to contribute in it, but is there any language specifications as most of the code are in JAVA here in this repo?

**Comment by Nexengineer** [comment]
No there is no language barrier. You can create a folder inside the respective topic and add questions. Only cavert, it should be an aligned question with the source/question statement.

**Comment by Aratrik-02** [comment]
Hey @Nexengineer I would also like to contribute some codes, could you assign me this issue?

**Comment by Aratrik-02** [comment]
Hey @Nexengineer I added today's LC question based on stack here #32

**Comment by Nexengineer** [comment]
@Aratrik-02, It is mostly an open-ended issue. You can directly contribute to the respective folder by just creating a pull request.

**Comment by harshil-1402** [comment]
Hello, I would like to contribute in this project, where can I find the problem statements for the same

**Comment by harshil-1402** [comment]
Hello, I would like to contribute in this project, where can I find the problem statements for the same, can you assign it to me.

**Comment by Nexengineer** [comment]
@harshil-1402 You can pick anything from Blind75 list and DSAproblem file present in same file

**Comment by neeraj542** [comment]
Sir, I can also work with this issue

**Comment by Nexengineer** [comment]
Go ahead ! Add a valid question and I will be marking pull request hacktoberfest-accepted @neeraj542

**Comment by harshil-1402** [comment]
So I can directly create a file and add questions there right?

**Comment by Nexengineer** [comment]
Yes @harshil-1402

**Comment by AlabhyaG** [comment]
Hello, @Nexengineer I wants to contribute on this issue. 
Can you please assign this to me.
