### ISSUE TITLE
Add questions related to array

### ISSUE THREAD

**Issue by Nexengineer** [Nexengineer/DSA-PREP#9]

**Comment by ArSin2002** [comment]
can i work on this??? @Nexengineer

**Comment by Nexengineer** [comment]
Go ahead dude

**Comment by Nexengineer** [comment]
please do raise a PR

**Comment by ArSin2002** [comment]
i have raised the PR for sortings in array @Nexengineer

**Comment by Nexengineer** [comment]
Merged

**Comment by naveenbisht31** [comment]
Hey @Nexengineer, I also want to add questions. Can you pls assign it to me.

**Comment by Nexengineer** [comment]
Assigned

**Comment by MuskanGarg24** [comment]
@Nexengineer  can you please assign me this!

**Comment by Nexengineer** [comment]
It is mostly an open-ended Issue. Who soever wants to work on this can work on it directly. This will be open till hacktoberfest lasts

**Comment by Siddhesh4501** [comment]
I will add Some array questions. Please merge it...

**Comment by Hanuvesh** [comment]
please assign me this task

**Comment by Nexengineer** [comment]
@Hanuvesh go ahead

**Comment by Shreyanshishere** [comment]
@Nexengineer please assign me this issue.

**Comment by Nexengineer** [comment]
sure @Shreyanshishere
